-- Migration: Create document_chunks table
CREATE TABLE IF NOT EXISTS document_chunks (
    id uuid PRIMARY KEY,
    topic_id uuid,
    embedding_json jsonb,
    session_id uuid,
    embedding USER-DEFINED,
    user_id uuid,
    timestamp timestamp without time zone,
    ingested boolean,
    ingested_at timestamp without time zone,
    uploaded_at timestamp without time zone,
    relevant_date date,
    openai_embedding USER-DEFINED,
    tokens integer,
    local_embedding bytea,
    updated_at timestamp without time zone,
    file_id uuid,
    folder_id uuid,
    chunk_index integer,
    created_at timestamp without time zone,
    size integer,
    project_id uuid,
    message_index integer,
    name text,
    content text,
    file_name text,
    description text,
    collection text,
    sharing text,
    file_path text,
    type text,
    status text,
    topic_name text,
    speaker_role text,
    file_content text
);
